# manage.py
#
# Django's command-line entry point.
#
# Written by hand rather than generated by `django-admin startproject`, because
# CLAUDE.md Section 5 requires line 1 of every file to be a path comment and the
# generated template does not carry one. Editing generated boilerplate into
# compliance costs the same as writing it, and this way nothing arrives unread.
#
# ALWAYS invoked through the explicit interpreter path (D-011):
#   .\.venv\Scripts\python.exe manage.py runserver 8020
#
# Never `python manage.py` - on this machine an unqualified `python` can reach the
# Microsoft Store alias stub, which prints an advertisement instead of running.

import os
import sys


def main():
    # The settings module is set here rather than assumed from the environment, so a
    # bare `manage.py` invocation works from a fresh clone with nothing exported.
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        # The overwhelmingly likely cause on this project is the wrong interpreter,
        # so the message says so rather than offering a generic install hint.
        raise ImportError(
            "Django could not be imported. Check that the command was run through "
            ".\\.venv\\Scripts\\python.exe and that requirements.txt is installed."
        ) from exc

    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()
