# tools\New-DotEnv.ps1
#
# Generates the .env that docker-compose.yml requires, with freshly generated keys.
#
# WHY THIS EXISTS: REQ-N-002 forbids committing any secret, and REQ-N-003 wants the
# system to start from a single command. D-026 resolves that tension by treating key
# generation as one-time configuration rather than a start-up step - and this script
# is what makes that resolution a command rather than a paragraph somebody has to
# follow by hand. A configuration step that is documented in prose is a configuration
# step that gets done differently each time.
#
# The generated file is gitignored. Nothing here ever reaches history.
#
# Usage (from the repo root):
#   .\tools\New-DotEnv.ps1
#   .\tools\New-DotEnv.ps1 -Force      # replace an existing .env
#
# REFUSES BY DEFAULT when .env already exists. D-003: changing QVS_SIGNING_KEY
# invalidates every signature already issued, so silently regenerating it would make
# every existing qualification record fail verification - a data-destroying default
# dressed up as convenience.

[CmdletBinding()]
param(
    # Replace an existing .env. Named rather than positional so it cannot be passed
    # by accident.
    [switch] $Force
)

$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
$EnvFile  = Join-Path $RepoRoot '.env'
$Python   = Join-Path $RepoRoot '.venv\Scripts\python.exe'

if ((Test-Path $EnvFile) -and (-not $Force)) {
    Write-Host 'REFUSED  <  .env already exists - re-run with -Force to replace it'
    Write-Host "  -> $EnvFile"
    exit 1
}

# D-011: the explicit interpreter path, never a bare `python`.
if (-not (Test-Path $Python)) {
    Write-Host "FAILED  <  no interpreter at $Python"
    Write-Host '  -> create the virtual environment first'
    exit 1
}

# secrets.token_urlsafe is the generator Django's own documentation points at, and
# the same one named in .env.example. 50 bytes of entropy, url-safe so no character
# in the value can confuse a dotenv parser or a shell.
$secretKey  = & $Python -c "import secrets; print(secrets.token_urlsafe(50))"
$signingKey = & $Python -c "import secrets; print(secrets.token_urlsafe(50))"

if (-not $secretKey -or -not $signingKey) {
    Write-Host 'FAILED  <  key generation produced nothing'
    Write-Host "  -> $Python"
    exit 1
}

# Only the two secrets. QVS_DEBUG, QVS_ALLOWED_HOSTS and QVS_DATABASE_PATH are
# properties of the deployment rather than of this machine, and docker-compose.yml
# sets them in its `environment` block where they override anything here. Putting
# them in both places is how the two copies drift apart - the same argument that
# removed the exception lists in D-012, D-018 and D-022.
$lines = @(
    '# .env - generated by tools\New-DotEnv.ps1. NEVER COMMITTED.',
    '#',
    '# REQ-N-002: .gitignore excludes this file and .dockerignore keeps it out of the',
    '# image build context, so the values below exist only on this machine.',
    '#',
    '# D-003: regenerating QVS_SIGNING_KEY invalidates every signature already issued.',
    '# Generated once, then kept.',
    '',
    "QVS_SECRET_KEY=$secretKey",
    "QVS_SIGNING_KEY=$signingKey"
)

# ASCII, matching D-018 and every other artefact this project writes.
Set-Content -Path $EnvFile -Value $lines -Encoding ASCII

Write-Host 'OK  <  .env written with two generated keys'
Write-Host "  -> $EnvFile"
