# Generated by Django 5.2.17 on 2026-09-10 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(editable=False, help_text='System-issued identifier, formatted QVS-XXXX-XXXX-XXXX-XXXX.', max_length=23, unique=True)),
                ('holder_name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('qualification_title', models.CharField(max_length=200)),
                ('award_date', models.DateField(help_text='The date the qualification was awarded by the institution.')),
                ('issued_at', models.DateTimeField(editable=False, help_text='When this record was registered in QVS. Covered by the signature.')),
                ('signature', models.CharField(editable=False, max_length=64)),
                ('issued_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='issued_qualifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'qualification',
                'verbose_name_plural': 'qualifications',
                'ordering': ['-issued_at'],
            },
        ),
    ]
