# Generated by Django 5.2.17 on 2026-09-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, help_text='When the verification was attempted.')),
                ('submitted_certificate_id', models.CharField(help_text='The certificate ID as submitted, after normalisation.', max_length=64)),
                ('outcome', models.CharField(help_text='VERIFIED, NOT FOUND or TAMPERED.', max_length=16)),
                ('actor_username', models.CharField(blank=True, help_text='The signed-in user, or blank for an anonymous attempt.', max_length=150)),
                ('remote_address', models.GenericIPAddressField(blank=True, help_text='The address the attempt came from, where the request carried one.', null=True)),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
